### ISSUE TITLE
precmd:6: unknown condition: -v

### ISSUE THREAD

**Issue by ghost** [martinrotter/powerless#1]
I'm getting `precmd:6: unknown condition: -v` without anything else in my `.zshrc` file. Any ideas? I'm on Fedora 25.

**Comment by martinrotter** [comment]
Check with latest revision, please.
`-v` is standard conditional statement in ZSH. See [here](http://zsh.sourceforge.net/Doc/Release/Conditional-Expressions.html) and search for `-v`.

**Comment by martinrotter** [comment]
I will check when I get home with clean profile on Arch Linux.

**Comment by martinrotter** [comment]
OK, can you try latest revision 5dc6996? I replaced `-v` with simple varible comparison. But, I am still not sure why this does not work for you. It works in plain zsh in Arch Linux.

Please, test and let me know.

**Comment by martinrotter** [comment]
I am closing, `-v` was changed to something else, it should work. :)

**Comment by ghost** [comment]
It works without issues!

**Comment by martinrotter** [comment]
Okay, thanks.
