### ISSUE TITLE
Different color for root account?

### ISSUE THREAD

**Issue by ghost** [martinrotter/powerless#2]
I moved from bash/powerline to zsh/powerless and I really like the speed, function and looks. But one thing I'm missing is the clear distinction between user accounts (blue) and root (red) that powerline has. My standard account does not have administrator rights, so I'm using root quite a lot and I want to avoid doing things in root by mistake. I'm curious what your thoughts are.

**Comment by martinrotter** [comment]
Indeed, I will highlight privileged accounts in some way. Maybe just printing background color of the username as red in case of root? Or do you have any other suggestions?

**Comment by martinrotter** [comment]
Btw, can you post here screnshot of the powerless prompt when you run it with root? I would like to check something out. Use latest powerless code, please. :)

**Comment by ghost** [comment]
Okay, great! [This](http://tinypic.com/r/ddm7mf/9) is how it looks. I included powerline in the screenshot. Red sounds good.

**Comment by martinrotter** [comment]
There was already support for different root prompt color, but it contained a bug. See now this screenshot. Left panel -> prompt character turns red once root account is there. Is this enough? Or do you prefer to colorize whole "user" segment?

![screenshot at 2017-03-05 19-29-17](https://cloud.githubusercontent.com/assets/1255302/23590099/291871b0-01da-11e7-905b-6d993d53fcba.png)

**Comment by ghost** [comment]
It's minimal, yet immediately clear. I like your approach and prefer it to colorizing the whole user segment.

**Comment by martinrotter** [comment]
Okay, perfectos.

**Comment by martinrotter** [comment]
Hello, just to ask something.

Now, powerless shows +- lines when there are some uncommitted changes in git repo. I think, would it be better to show state icons instead of numbers?

I mean something like [this](https://raw.githubusercontent.com/arialdomartini/oh-my-git-gh-pages/master/images/samples/06-tris-colors.jpg), those icons in the left part of the prompt.

For example, when repo contains uncommitted changes -> show some icon. If repo contains unversioned files -> show some icons. Etc. Still main think is the SPEED of the prompt, I am not going to clutter it.

What you think?

**Comment by ghost** [comment]
I see what you mean. The +/- line gives a nice indication of the amount of code that is still uncommitted, but is not very informative otherwise. So in your example if I do `git add untracked_file1` but leave `untracked_file2` untracked, it's going to show one icon for the untracked file and one icon saying that I still need to commit and push? I'm not a heavy git user, but some visual aid is always welcome, as long as it stays uncluttered and informative.

**Comment by martinrotter** [comment]
Yes, I am still not decided which icons I will include.

I will first test if it is fast, I plan icons for these situations in Git repo:
 - uncommitted changes,
 - untracked files.

**Comment by ghost** [comment]
Something similar is done here (though they use characters instead of icons): https://github.com/oh-my-fish/theme-bobthefish.

**Comment by martinrotter** [comment]
OK, I managed to get fast multiple infos about Git if current PWD is Git repo. But I was not able to find approriate and good-looking font characters to represent those situatios, so far, I have these:

U - there is an untracked file in the repo,
M - there are some modified and uncommitted files in the repo,
A - there are newly added and uncommitted files,
D - there are some deleted files,
R - all changes are committed and repo is ready to PUSH.

![bez nazvu](https://cloud.githubusercontent.com/assets/1255302/23783812/83c6878c-055e-11e7-8cb5-28e5c37f906a.png)

**Comment by martinrotter** [comment]
So what you think?

**Comment by martinrotter** [comment]
I mean, there are certainly nice glyphs to use, but some powerline fonts have them, some do not. I would like to stick with DejaVu Sans Mono for powerline which is used by many users and is some sort of reference font for powerline.

**Comment by martinrotter** [comment]
I can put separator among those characters, like this for example.

![bez nazvu](https://cloud.githubusercontent.com/assets/1255302/23784463/6dc5f964-0562-11e7-8759-aacd5f347eed.png)

**Comment by martinrotter** [comment]
I merged changes into [master].
