### ISSUE TITLE
uname: illegal option -- o

### ISSUE THREAD

**Issue by tlnagy** [martinrotter/powerless#3]
Great little program! I noticed a little problem when sourcing `utilites.zsh`, I get the following error:

```
uname: illegal option -- o
usage: uname [-amnprsv]
```

I'm on OS X 10.12.5 using zsh 5.3.1

**Comment by martinrotter** [comment]
It seems that macosx version of `uname` does not support that option. Will fix.

**Comment by martinrotter** [comment]
Can you give me outputs of:
`uname`
`uname -a`
`uname -s`

**Comment by martinrotter** [comment]
I tried to fix, let me know if it works.

**Comment by tlnagy** [comment]
```

**Comment by tlnagy** [comment]
```
 $ uname
Darwin

 $ uname -a
Darwin otp587239ots.ucsf.edu 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

 $ uname -s
Darwin
```

The latest master still crashes because there is still a call to `uname -o` here: https://github.com/martinrotter/powerless/commit/39b9c19d426f796d73445b751dd88a4a65e86fd9#diff-980e02a5e8e85fdbaf9628599cd1eb71L17

**Comment by martinrotter** [comment]
Forgot to remove. Should work, test pls.

**Comment by tlnagy** [comment]
That seems to fix it! Thanks
