### ISSUE TITLE
Huge amount of extra whitespace

### ISSUE THREAD

**Issue by tlnagy** [martinrotter/powerless#4]
```






 tamasnagy  ~/dotfiles/zsh/powerless  master
 $ echo test
test






 tamasnagy  ~/dotfiles/zsh/powerless  master
 $
```

There seems to be a lot of extra newlines displayed in iTerm2 on Mac. Any thoughts how why this might be happening?

**Comment by martinrotter** [comment]
Well, this is weird, but I will investigate. Does not happen on any terminal emulator on Linux/Windows I have tried so far.

**Comment by martinrotter** [comment]
Does setting `TERM=xterm-256color` before you source powerless scripts help?

**Comment by martinrotter** [comment]
Does the bug happen with default Mac terminal emulator?

**Comment by martinrotter** [comment]
Please, test latest master.

**Comment by tlnagy** [comment]
It was in the default terminal emulator too, but this seems to fix it:

![image](https://user-images.githubusercontent.com/1661487/29629644-6d357402-87ee-11e7-9e03-40d1b08fd3e2.png)

Thanks! 👍
