### ISSUE TITLE
New terminal windows cause powerless to throw error

### ISSUE THREAD

**Issue by tlnagy** [martinrotter/powerless#5]
```
get-last-code:1: unknown condition: -v
 tamasnagy pwd
/Users/tamasnagy/Downloads/tamas

get-last-code:1: unknown condition: -v
 tamasnagy echo test
test

get-last-code:1: unknown condition: -v
 tamasnagy
```

I believe the following lines are causing this problem: https://github.com/martinrotter/powerless/blob/master/powerless.zsh#L41-L43. This happens whenever I open a new terminal window or tab in both iTerm2 and the default Mac terminal. Thanks for your help!

**Comment by martinrotter** [comment]
Does new terminal window really open ZSH as its shell? Really? Make sure to check it and let me know. Because ZSH supports that option of course:

`-v varname
true if shell variable varname is set.`

You can check if zsh is active shell in new windows like this: `echo $SHELL`.

**Comment by martinrotter** [comment]
Followup: Does the bug happen in default mac terminal emulator too?

**Comment by martinrotter** [comment]
I tried to fix, test if it works, please.

**Comment by tlnagy** [comment]
This fixed it! Thanks 👍
