### ISSUE TITLE
Different color for when head is clean?

### ISSUE THREAD

**Issue by tlnagy** [martinrotter/powerless#6]
This is more of a preference, but what do you think of changing the git status indicator color to green if the HEAD is clean? So the last line of your example gif would have a green indicator instead of an orange one.

**Comment by martinrotter** [comment]
Well, the scripts is now using 8/16 default color names. See [here](https://github.com/martinrotter/powerless/blob/master/powerless.zsh#L10).

You can override any of those colors, but that is probably not what you want. So, maybe you want orange color when git state is dirty and green when it is clean?

**Comment by tlnagy** [comment]
> So, maybe you want orange color when git state is dirty and green when it is clean?

Exactly. The exclamation point that currently indicates this is too subtle IMO. Plus there's something weird about having the good/clean state be orange.

**Comment by martinrotter** [comment]
Indeed, will add this tomorrow.
